"""The law families — every gap a live model exposed stays closed forever."""
from montology_gen.instruments import fingerprint, package_surface
from montology_gen.laws import (GROUNDING, STRUCTURAL, echoes, provenance_current,
                                substance, tools_exist, word_laws)

SURFACE = {"package": "pkg", "functions": [
    {"name": "serp_search", "signature": "serp_search(k: str) -> str",
     "doc": "Live Google organic results for a keyword.", "module": "t", "infra": False}]}

GOOD = """---
name: demo
description: What the tool covers and when to reach for it.
---

<!-- GENERATED by monty gen instruments=sha256:{h} -->

## `serp_search`

`serp_search(k: str) -> str`

Ask it who ranks for a phrase; pass the query a customer would actually type,
and read position before celebrating presence.
"""


def _check(text, laws):
    return [f"{l.name}: {w}" for l in laws if (w := l.check(text))]


def test_structural_pass_and_each_failure_mode():
    text = GOOD.format(h="a" * 16)
    assert _check(text, STRUCTURAL) == []
    assert any("frontmatter" in f for f in _check("no fences at all", STRUCTURAL))
    assert any("description" in f for f in _check("---\nname: demo\n---\nbody", STRUCTURAL))
    assert any("name" in f for f in _check("---\nname: Bad_Name\ndescription: x\n---\nbody", STRUCTURAL))


def test_ghost_tools_are_caught():
    law = tools_exist(SURFACE)
    assert law.check(GOOD.format(h="a" * 16)) is None
    got = law.check(GOOD.format(h="a" * 16) + "\nalso try `magic_rankings(`")
    assert got and "magic_rankings" in got


def test_substance_catches_filler_and_spec_parrots():
    """gemma3:270m shipped a name-as-method; qwen3:0.6b parroted the spec.
    Both measured live 2026-08-10; both must fail forever."""
    spec = "Two to four plain sentences of METHOD for this one tool."
    law = substance(SURFACE, (spec,))
    filler = GOOD.format(h="a" * 16).replace(
        "Ask it who ranks for a phrase; pass the query a customer would actually type,\nand read position before celebrating presence.",
        "serp_search")
    assert law.check(filler) and "filler" in law.check(filler)
    parrot = GOOD.format(h="a" * 16).replace(
        "Ask it who ranks for a phrase; pass the query a customer would actually type,\nand read position before celebrating presence.",
        spec)
    assert law.check(parrot)
    assert law.check(GOOD.format(h="a" * 16)) is None


def test_echoes_window():
    assert echoes("one two three four five six seven eight nine", "zzz one two three four five six seven eight yyy")
    assert not echoes("completely different words here now then again more", "one two three four five six seven eight")


def test_drift_gate_fresh_vs_stale():
    h = fingerprint(SURFACE)
    law = provenance_current(h)
    assert law.check(f"<!-- GENERATED by monty gen instruments=sha256:{h} -->") is None
    got = law.check("<!-- GENERATED by monty gen instruments=sha256:deadbeefdeadbeef -->")
    assert got and "STALE" in got and "regenerate" in got


def test_word_laws_catch_the_bare_word():
    """The 270M returned just 'campaign' and it PASSED once. Never again."""
    laws = word_laws(lambda name: [])
    def run(text):
        return [w for l in laws if (w := l.check(text))]
    assert run("campaign")  # bare word
    assert run("campaign: ads")  # too thin
    assert run("flight: uses DataForSEO daily")  # vendor
    assert not run("flight: the dated window a campaign's ads actually run in")


def test_grounding_env_and_provenance():
    text = GOOD.format(h="a" * 16)
    assert _check(text, GROUNDING) == []
    assert any("env" in f for f in _check(text + "\nexport TOTALLY_FAKE_KEY=x", GROUNDING))
    assert any("provenance" in f for f in _check(text.replace("GENERATED by monty gen", "x"), GROUNDING))


def test_real_package_surface_reads_ast():
    surface = package_surface("tools/dataforseo/src/montology_dataforseo")
    names = {f["name"] for f in surface["functions"]}
    assert {"serp_search", "keyword_ideas"} <= names
    assert any(f["infra"] for f in surface["functions"] if f["name"] == "mellea_tools")
