"""The law families — every gap a live model exposed stays closed forever."""
from montology_gen.instruments import fingerprint
from montology_gen.laws import STRUCTURAL, provenance_current, word_laws

GOOD = """---
name: words
description: What the vocabulary covers and when to check it.
---

<!-- GENERATED by monty gen sync instruments=sha256:{h} -->

## The words

One word, one meaning.
"""


def _check(text, laws):
    return [f"{l.name}: {w}" for l in laws if (w := l.check(text))]


def test_structural_pass_and_each_failure_mode():
    text = GOOD.format(h="a" * 16)
    assert _check(text, STRUCTURAL) == []
    assert any("frontmatter" in f for f in _check("no fences at all", STRUCTURAL))
    assert any("description" in f for f in _check("---\nname: demo\n---\nbody", STRUCTURAL))
    assert any("name" in f for f in _check("---\nname: Bad_Name\ndescription: x\n---\nbody", STRUCTURAL))


def test_drift_gate_fresh_vs_stale():
    h = fingerprint({"words": ["thread"]})
    law = provenance_current(h)
    assert law.check(f"<!-- GENERATED by monty gen sync instruments=sha256:{h} -->") is None
    got = law.check("<!-- GENERATED by monty gen sync instruments=sha256:deadbeefdeadbeef -->")
    assert got and "STALE" in got and "monty sync" in got


def test_word_laws_catch_the_bare_word():
    """The 270M returned just 'campaign' and it PASSED once. Never again."""
    laws = word_laws(lambda name: [])

    def run(text):
        return [w for l in laws if (w := l.check(text))]

    assert run("cell")                              # bare word
    assert run("cell: box")                         # too thin
    assert run("cell: a row stored in sqlite")      # vendor as vocabulary
    assert not run("cell: the network-blocked box a run's code executes in")


def test_word_laws_respect_the_check(onto_db):
    from montology_ontology import check

    onto_db.add("cell", "the sandbox", kind="core")
    laws = word_laws(check)
    got = [w for l in laws if (w := l.check("cell: something else entirely here"))]
    assert got and "spoken for" in got[0]
